<?php
$application = $this->getApplication();
$request = $this->getRequest();
$valueId = Cabride_Model_Cabride::getCurrentValueId();
$isEdit = $this->getEdit();

$settings = (new Cabride_Model_Cabride())
    ->find($valueId, "value_id");

$formDriver = new Cabride_Form_Driver();
$formDriver->setValueId($valueId);
$formDriver->loadVehicles($valueId);

if ($isEdit) {
    $formDriver->populate($this->getDriver()->getData());
}

?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="driver_form"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php
                        if ($isEdit) {
                            echo p__("cabride", "Edit driver");
                        } else {
                            echo p__("cabride", "Create driver");
                        }
                    ?>
                </h3>
                <div class="subcontent content-color">
                    <div id="form-driver"
                         class="col-md-12">

                        <div>
                            <a href="<?php echo __path("/cabride/dashboard/drivers"); ?>"
                               class="toggle-form btn color-blue pull-right">
                                <?php echo p__("cabride", "Go back"); ?>
                            </a>
                        </div>

                        <div>
                            <?php echo $formDriver ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function () {
    bindForms("#driver_form");
});
</script>
