<?php

?>

<div class="list">
    <div class="alert alert-info">
        <?php echo p__("cabride", "CabRide management & configuration is done through the extended Dashboard / Menu"); ?>
        <br />
        <?php echo p__("cabride", "Go to") ?>
        <a href="/cabride/dashboard"
           target="_blank"
           class="btn btn-sm btn-default color-green"><?php echo p__("cabride", "Dashboard") ?></a>
        <?php echo p__("cabride", "or") ?>
        <a href="/cabride/dashboard/settings"
           target="_blank"
           class="btn btn-sm btn-default color-green"><?php echo p__("cabride", "Settings") ?></a>
    </div>
</div>
