<?php
$optionValue = $this->getOptionValue();

$formDefault = new Cabride_Form_Cabride();

$deleteForm = new Cabride_Form_Cabride();

$collection = [];

/**$wordpress = (new Wordpress2_Model_Wordpress())
    ->find($optionValue->getId(), 'value_id');

// Create the WordPress if it doesn't yet exists.
if (!$wordpress->getId()) {
    $wordpress = new Wordpress2_Model_Wordpress();
    $wordpress
        ->setValueId($optionValue->getId())
        ->save();
}

$wordpressHasUrl = !empty(trim($wordpress->getData('url')));

$formWordpress = new Wordpress2_Form_Wordpress();
$formWordpress->populate($wordpress->getData());
$formWordpress
    ->getElement('password')
    ->setValue($wordpress->getPassword());

$formQuery = new Wordpress2_Form_Query();
$formQuery->populate(
    [
        'value_id' => $optionValue->getId()
    ]
);

$formSettings = new Wordpress2_Form_Settings();
$formSettings->populate($wordpress->getData());

$queries = (new Wordpress2_Model_Query())
    ->findAll(
        [
            'value_id' => $optionValue->getId()
        ],
        'position ASC'
    );

// Display sort fields only if queries are not grouped!
if ($wordpress->getData('group_queries') !== '1') {
    $formQuery->addSortFields();
}

$gotCategories = false;
try {
    $wordpressApi = new Wordpress2_Model_WordpressApi();
    $wordpressApi->init(
        $wordpress->getData('url'),
        $wordpress->getData('login'),
        $wordpress->getData('password')
    );

    $categories = $wordpressApi->getCategories();

    $formQuery
        ->loadCategories($categories);

    $gotCategories = (sizeof($categories) > 0);

} catch (Exception $e) {
    $gotCategories = false;
}

$gotPages = false;
try {
    $wordpressApi = new Wordpress2_Model_WordpressApi();
    $wordpressApi->init(
        $wordpress->getData('url'),
        $wordpress->getData('login'),
        $wordpress->getData('password')
    );

    $pages = $wordpressApi->getAllPages();

    $formQuery
        ->loadPages($pages);

    $gotPages = (sizeof($pages) > 0);

} catch (Exception $e) {
    $gotPages = false;
}

$formQuery->createSubmit();*/

?>

<div id="list"
     class="Cabride">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs"
        role="tablist">
        <li role="presentation"
            class="active">
            <a href="#cabride"
               aria-controls="cabride"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-folder-open-o"></i> <?php echo __('Cabride'); ?>
            </a>
        </li>
		<li role="presentation">
            <a href="#client"
               aria-controls="client"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-folder-open-o"></i> <?php echo __('Client'); ?>
            </a>
        </li>
		<li role="presentation">
            <a href="#driver"
               aria-controls="driver"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-folder-open-o"></i> <?php echo __('Driver'); ?>
            </a>
        </li>
		<li role="presentation">
            <a href="#payment"
               aria-controls="payment"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-folder-open-o"></i> <?php echo __('Payment'); ?>
            </a>
        </li>
		<li role="presentation">
            <a href="#payout"
               aria-controls="payout"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-folder-open-o"></i> <?php echo __('Payout'); ?>
            </a>
        </li>
		<li role="presentation">
            <a href="#request"
               aria-controls="request"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-folder-open-o"></i> <?php echo __('Request'); ?>
            </a>
        </li>
		<li role="presentation">
            <a href="#vehicle"
               aria-controls="vehicle"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-folder-open-o"></i> <?php echo __('Vehicle'); ?>
            </a>
        </li>
        <li role="presentation">
            <a href="#design"
               aria-controls="design"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-pencil"></i>
                <?php echo __('Design') ?>
            </a>
        </li>
    </ul>

    <div class="tab-content">
                <!-- START Cabride TAB -->
        <div role="tabpanel"
             class="tab-pane active"
             id="cabride">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Add %s', 'Cabride'); ?>
                    <button type="button"
                            class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formDefault; ?>
                </div>
            </div>

            <?php if (sizeof($collection) > 0): ?>
                <div class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __('Manage elements'); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable"><?php echo __("Value Id"); ?></th>
									<th class="sortable"><?php echo __("Distance Unit"); ?></th>
									<th class="sortable"><?php echo __("Search Timeout"); ?></th>
									<th class="sortable"><?php echo __("Search Radius"); ?></th>
									<th class="sortable"><?php echo __("Accepted Payments"); ?></th>
									<th class="sortable"><?php echo __("Commission"); ?></th>
									<th class="sortable"><?php echo __("Course Mode"); ?></th>
									<th class="sortable"><?php echo __("Pricing Mode"); ?></th>
									<th class="sortable"><?php echo __("Driver Can Register"); ?></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($collection as $item) : ?>
                                    <tr id="cabride_manage_element_<?php echo $item->getId(); ?>"
                                        class="cabride-manage-element sb-pager">
                                        <td><?php echo $item->getData('value_id'); ?></td>
										<td><?php echo $item->getData('distance_unit'); ?></td>
										<td><?php echo $item->getData('search_timeout'); ?></td>
										<td><?php echo $item->getData('search_radius'); ?></td>
										<td><?php echo $item->getData('accepted_payments'); ?></td>
										<td><?php echo $item->getData('commission'); ?></td>
										<td><?php echo $item->getData('course_mode'); ?></td>
										<td><?php echo $item->getData('pricing_mode'); ?></td>
										<td><?php echo filter_var($item->getData('driver_can_register'), FILTER_VALIDATE_BOOLEAN) ? __("Yes") : __("No"); ?></td>
                                        <td class="edit-action open-edit"
                                            data-id="cabride_<?php echo $item->getId(); ?>"
                                            data-form-url="<?php echo __path('/cabride/cabride/loadform', [
                                                'cabride_id' => $item->getId(),
                                                'value_id' => $optionValue->getId()
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                            $deleteForm->setAttrib('data-rowid', 'cabride_manage_element_' . $item->getId());
                                            $deleteForm
                                                ->getElement('cabride_id')
                                                ->setValue($item->getId());

                                            echo $deleteForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="cabride_<?php echo $item->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="6">
                                            <p class="close-edit"
                                               data-id="cabride_<?php echo $item->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo __('Close') ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- /END Cabride TAB -->
        <!-- START Cabride TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="client">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Add %s', 'Client'); ?>
                    <button type="button"
                            class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formDefault; ?>
                </div>
            </div>

            <?php if (sizeof($collection) > 0): ?>
                <div class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __('Manage elements'); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable"><?php echo __("Customer Id"); ?></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($collection as $item) : ?>
                                    <tr id="cabride_client_manage_element_<?php echo $item->getId(); ?>"
                                        class="cabride_client-manage-element sb-pager">
                                        <td><?php echo $item->getData('customer_id'); ?></td>
                                        <td class="edit-action open-edit"
                                            data-id="cabride_client_<?php echo $item->getId(); ?>"
                                            data-form-url="<?php echo __path('/cabride/client/loadform', [
                                                'client_id' => $item->getId(),
                                                'value_id' => $optionValue->getId()
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                            $deleteForm->setAttrib('data-rowid', 'cabride_client_manage_element_' . $item->getId());
                                            $deleteForm
                                                ->getElement('client_id')
                                                ->setValue($item->getId());

                                            echo $deleteForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="cabride_client_<?php echo $item->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="6">
                                            <p class="close-edit"
                                               data-id="cabride_client_<?php echo $item->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo __('Close') ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- /END Cabride TAB -->
        <!-- START Cabride TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="driver">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Add %s', 'Driver'); ?>
                    <button type="button"
                            class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formDefault; ?>
                </div>
            </div>

            <?php if (sizeof($collection) > 0): ?>
                <div class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __('Manage elements'); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable"><?php echo __("Customer Id"); ?></th>
									<th class="sortable"><?php echo __("Vehicle Id"); ?></th>
									<th class="sortable"><?php echo __("Vehicle Model"); ?></th>
									<th class="sortable"><?php echo __("Vehicle License Plate"); ?></th>
									<th class="sortable"><?php echo __("Driver License"); ?></th>
									<th class="sortable"><?php echo __("Driver Photo"); ?></th>
									<th class="sortable"><?php echo __("Base Address"); ?></th>
									<th class="sortable"><?php echo __("Pickup Radius"); ?></th>
									<th class="sortable"><?php echo __("Status"); ?></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($collection as $item) : ?>
                                    <tr id="cabride_driver_manage_element_<?php echo $item->getId(); ?>"
                                        class="cabride_driver-manage-element sb-pager">
                                        <td><?php echo $item->getData('customer_id'); ?></td>
										<td><?php echo $item->getData('vehicle_id'); ?></td>
										<td><?php echo $item->getData('vehicle_model'); ?></td>
										<td><?php echo $item->getData('vehicle_license_plate'); ?></td>
										<td><?php echo $item->getData('driver_license'); ?></td>
										<td><?php echo $item->getData('driver_photo'); ?></td>
										<td><?php echo $item->getData('base_address'); ?></td>
										<td><?php echo $item->getData('pickup_radius'); ?></td>
										<td><?php echo $item->getData('status'); ?></td>
                                        <td class="edit-action open-edit"
                                            data-id="cabride_driver_<?php echo $item->getId(); ?>"
                                            data-form-url="<?php echo __path('/cabride/driver/loadform', [
                                                'driver_id' => $item->getId(),
                                                'value_id' => $optionValue->getId()
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                            $deleteForm->setAttrib('data-rowid', 'cabride_driver_manage_element_' . $item->getId());
                                            $deleteForm
                                                ->getElement('driver_id')
                                                ->setValue($item->getId());

                                            echo $deleteForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="cabride_driver_<?php echo $item->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="6">
                                            <p class="close-edit"
                                               data-id="cabride_driver_<?php echo $item->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo __('Close') ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- /END Cabride TAB -->
        <!-- START Cabride TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="payment">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Add %s', 'Payment'); ?>
                    <button type="button"
                            class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formDefault; ?>
                </div>
            </div>

            <?php if (sizeof($collection) > 0): ?>
                <div class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __('Manage elements'); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable"><?php echo __("Amount"); ?></th>
									<th class="sortable"><?php echo __("Method"); ?></th>
									<th class="sortable"><?php echo __("Status"); ?></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($collection as $item) : ?>
                                    <tr id="cabride_payment_manage_element_<?php echo $item->getId(); ?>"
                                        class="cabride_payment-manage-element sb-pager">
                                        <td><?php echo $item->getData('amount'); ?></td>
										<td><?php echo $item->getData('method'); ?></td>
										<td><?php echo $item->getData('status'); ?></td>
                                        <td class="edit-action open-edit"
                                            data-id="cabride_payment_<?php echo $item->getId(); ?>"
                                            data-form-url="<?php echo __path('/cabride/payment/loadform', [
                                                'payment_id' => $item->getId(),
                                                'value_id' => $optionValue->getId()
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                            $deleteForm->setAttrib('data-rowid', 'cabride_payment_manage_element_' . $item->getId());
                                            $deleteForm
                                                ->getElement('payment_id')
                                                ->setValue($item->getId());

                                            echo $deleteForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="cabride_payment_<?php echo $item->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="6">
                                            <p class="close-edit"
                                               data-id="cabride_payment_<?php echo $item->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo __('Close') ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- /END Cabride TAB -->
        <!-- START Cabride TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="payout">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Add %s', 'Payout'); ?>
                    <button type="button"
                            class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formDefault; ?>
                </div>
            </div>

            <?php if (sizeof($collection) > 0): ?>
                <div class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __('Manage elements'); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable"><?php echo __("Driver Id"); ?></th>
									<th class="sortable"><?php echo __("Amount"); ?></th>
									<th class="sortable"><?php echo __("Method"); ?></th>
									<th class="sortable"><?php echo __("Status"); ?></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($collection as $item) : ?>
                                    <tr id="cabride_payout_manage_element_<?php echo $item->getId(); ?>"
                                        class="cabride_payout-manage-element sb-pager">
                                        <td><?php echo $item->getData('driver_id'); ?></td>
										<td><?php echo $item->getData('amount'); ?></td>
										<td><?php echo $item->getData('method'); ?></td>
										<td><?php echo $item->getData('status'); ?></td>
                                        <td class="edit-action open-edit"
                                            data-id="cabride_payout_<?php echo $item->getId(); ?>"
                                            data-form-url="<?php echo __path('/cabride/payout/loadform', [
                                                'payout_id' => $item->getId(),
                                                'value_id' => $optionValue->getId()
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                            $deleteForm->setAttrib('data-rowid', 'cabride_payout_manage_element_' . $item->getId());
                                            $deleteForm
                                                ->getElement('payout_id')
                                                ->setValue($item->getId());

                                            echo $deleteForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="cabride_payout_<?php echo $item->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="6">
                                            <p class="close-edit"
                                               data-id="cabride_payout_<?php echo $item->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo __('Close') ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- /END Cabride TAB -->
        <!-- START Cabride TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="request">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Add %s', 'Request'); ?>
                    <button type="button"
                            class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formDefault; ?>
                </div>
            </div>

            <?php if (sizeof($collection) > 0): ?>
                <div class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __('Manage elements'); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable"><?php echo __("Client Id"); ?></th>
									<th class="sortable"><?php echo __("Status"); ?></th>
									<th class="sortable"><?php echo __("Cost"); ?></th>
									<th class="sortable"><?php echo __("From Address"); ?></th>
									<th class="sortable"><?php echo __("From Lat"); ?></th>
									<th class="sortable"><?php echo __("From Lng"); ?></th>
									<th class="sortable"><?php echo __("To Address"); ?></th>
									<th class="sortable"><?php echo __("To Lat"); ?></th>
									<th class="sortable"><?php echo __("To Lng"); ?></th>
									<th class="sortable"><?php echo __("Request Mode"); ?></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($collection as $item) : ?>
                                    <tr id="cabride_request_manage_element_<?php echo $item->getId(); ?>"
                                        class="cabride_request-manage-element sb-pager">
                                        <td><?php echo $item->getData('client_id'); ?></td>
										<td><?php echo $item->getData('status'); ?></td>
										<td><?php echo $item->getData('cost'); ?></td>
										<td><?php echo $item->getData('from_address'); ?></td>
										<td><?php echo $item->getData('from_lat'); ?></td>
										<td><?php echo $item->getData('from_lng'); ?></td>
										<td><?php echo $item->getData('to_address'); ?></td>
										<td><?php echo $item->getData('to_lat'); ?></td>
										<td><?php echo $item->getData('to_lng'); ?></td>
										<td><?php echo $item->getData('request_mode'); ?></td>
                                        <td class="edit-action open-edit"
                                            data-id="cabride_request_<?php echo $item->getId(); ?>"
                                            data-form-url="<?php echo __path('/cabride/request/loadform', [
                                                'request_id' => $item->getId(),
                                                'value_id' => $optionValue->getId()
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                            $deleteForm->setAttrib('data-rowid', 'cabride_request_manage_element_' . $item->getId());
                                            $deleteForm
                                                ->getElement('request_id')
                                                ->setValue($item->getId());

                                            echo $deleteForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="cabride_request_<?php echo $item->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="6">
                                            <p class="close-edit"
                                               data-id="cabride_request_<?php echo $item->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo __('Close') ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- /END Cabride TAB -->
        <!-- START Cabride TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="vehicle">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Add %s', 'Vehicle'); ?>
                    <button type="button"
                            class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formDefault; ?>
                </div>
            </div>

            <?php if (sizeof($collection) > 0): ?>
                <div class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __('Manage elements'); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable"><?php echo __("Type"); ?></th>
									<th class="sortable"><?php echo __("Base Fare"); ?></th>
									<th class="sortable"><?php echo __("Distance Fare"); ?></th>
									<th class="sortable"><?php echo __("Time Fare"); ?></th>
									<th class="sortable"><?php echo __("Base Address"); ?></th>
									<th class="sortable"><?php echo __("Is Visible"); ?></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($collection as $item) : ?>
                                    <tr id="cabride_vehicle_manage_element_<?php echo $item->getId(); ?>"
                                        class="cabride_vehicle-manage-element sb-pager">
                                        <td><?php echo $item->getData('type'); ?></td>
										<td><?php echo $item->getData('base_fare'); ?></td>
										<td><?php echo $item->getData('distance_fare'); ?></td>
										<td><?php echo $item->getData('time_fare'); ?></td>
										<td><?php echo $item->getData('base_address'); ?></td>
										<td><?php echo filter_var($item->getData('is_visible'), FILTER_VALIDATE_BOOLEAN) ? __("Yes") : __("No"); ?></td>
                                        <td class="edit-action open-edit"
                                            data-id="cabride_vehicle_<?php echo $item->getId(); ?>"
                                            data-form-url="<?php echo __path('/cabride/vehicle/loadform', [
                                                'vehicle_id' => $item->getId(),
                                                'value_id' => $optionValue->getId()
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                            $deleteForm->setAttrib('data-rowid', 'cabride_vehicle_manage_element_' . $item->getId());
                                            $deleteForm
                                                ->getElement('vehicle_id')
                                                ->setValue($item->getId());

                                            echo $deleteForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="cabride_vehicle_<?php echo $item->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="6">
                                            <p class="close-edit"
                                               data-id="cabride_vehicle_<?php echo $item->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo __('Close') ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- /END Cabride TAB -->

        <!-- START DESIGN TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="design">
            <?php echo $this->importLayout($optionValue, false); ?>

            <?php echo $this->importBackground($optionValue, false); ?>
        </div>
        <!-- /END DESIGN TAB -->
    </div>
</div>


<link href="/app/sae/modules/Cabride/resources/design/desktop/flat/template/cabride/application/edit.css"
      media="screen"
      rel="stylesheet"
      type="text/css" />
<script type="text/javascript">
    var valueId = '<?php echo $optionValue->getId() ?>';
</script>
<script type="text/javascript"
        src="/app/sae/modules/Cabride/resources/design/desktop/flat/template/cabride/application/edit.js">
</script>