<?php

use Cabride\Model\Cabride;
use Cabride\Model\Driver;

$application = $this->getApplication();
$request = $this->getRequest();
$valueId = Cabride::getCurrentValueId();

$drivers = (new Driver())
    ->findAll(["value_id" => $valueId]);

?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="driver_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "Drivers"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">
                        <table class="table content-white-bkg sb-pager margin-top">
                            <thead>
                            <tr class="border-grey">
                                <th class="sortable"><?php echo p__("cabride", "ID"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Customer ID"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Vehicle ID"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Vehicle model"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "License plate"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Driving license"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Photo"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Base address"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Pickup radius"); ?></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($drivers as $driver): ?>
                                <tr class="sb-pager">
                                    <td><?php echo $driver->getId(); ?></td>
                                    <td><?php echo $driver->getCustomerId(); ?></td>
                                    <td><?php echo $driver->getVehicleId(); ?></td>
                                    <td><?php echo $driver->getVehicleModel(); ?></td>
                                    <td><?php echo $driver->getVehicleLicensePlate(); ?></td>
                                    <td><?php echo $driver->getDriverLicense(); ?></td>
                                    <td><?php echo $driver->getDriverPhoto(); ?></td>
                                    <td><?php echo $driver->getBaseAddress(); ?></td>
                                    <td><?php echo $driver->getPickupRadius(); ?></td>
                                    <td class="text-right">
                                        <a class="btn btn-xs btn-info"
                                           href="<?php echo __path("/cabride/driver/edit", [
                                               "driver_id" => $driver->getId()
                                           ]); ?>">
                                            <?php echo p__("cabride", "EDIT") ?>
                                        </a>
                                        <a class="btn btn-xs btn-danger delete-driver"
                                           data-id="<?php echo $driver->getId(); ?>">
                                            <?php echo p__("cabride", "DELETE") ?>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="8">
                                    <?php echo p__("cabride", "No results for your search.") ?>
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var search_placeholder = '<?php echo p__js("cabride","Search ...", "'") ?>';
    $(document).ready(function () {
        bindForms("#driver_content");

        $("table.sb-pager").sbpager({
            with_search: true,
            search_placeholder: search_placeholder
        });

        let deleteDriver = $(".delete-driver");

        deleteDriver.off("click");
        deleteDriver.on("click", function () {
            let button = $(this);
            let driverId = button.attr("data-id");
            swal({
                html: true,
                title: '<?php echo p__js("cabride", "Delete driver", "'") ?>',
                text: '<?php echo p__js("cabride","Are you sure?", "'") ?>',
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: true,
                confirmButtonColor: '#ff3a2e',
                confirmButtonText: '<?php echo p__js("cabride","Yes, Delete", "'") ?>',
                cancelButtonText: '<?php echo p__js("cabride","No, go back!", "'") ?>',
            }, function (value) {
                if (value === false) {
                    return;
                }

                formget(
                    "/cabride/driver/deletepost",
                    {
                        'driver_id': driverId
                    },
                    function (data) {
                        // Success!
                        feature_form_success(data.message);
                        setTimeout(function () {
                            location.reload();
                        }, 3000);
                    },
                    function (data) {
                        feature_form_error(data.message);
                    });

                swal.close();
                return true;
            });
        });
    });
</script>
