<?php

use Cabride\Model\Cabride;
use Cabride\Model\Field;
use Cabride\Form\Field as FormField;
use Cabride\Form\Field\Delete as DeleteFormField;

$application = $this->getApplication();
$request = $this->getRequest();
$valueId = Cabride::getCurrentValueId();
$cabride = Cabride::getCurrent();

$formField = (new FormField())
    ->setValueId($valueId);

$fields = (new Field())->findAll(
    [
        "value_id = ?" => $valueId
    ],
    [
        "position ASC"
    ]
);

$deleteFieldForm = (new DeleteFormField())
    ->setValueId($valueId);

$formIsEnabled = (boolean) $cabride->getEnableCustomForm() == "1";

?>

<div class="row"
     id="fields">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="settings_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "Form configuration"); ?>
                </h3>
                <div class="subcontent content-color">

                    <div class="col-md-12">
                        <div class="alert alert-warning">
                            <?php echo p__("cabride", "The custom form is disabled in your settings, and will not be visible inside the application.") ?>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo p__("cabride", "Add a field") ?>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <?php echo $formField; ?>
                        </div>
                    </div>

                    <?php if ($fields->count() > 0): ?>
                    <div class="col-md-12"
                         style="margin-top: 20px;">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo p__("cabride", "Manage fields") ?>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager table-fields">
                                <thead>
                                <tr class="border-grey">
                                    <th style="width:32px;"></th>
                                    <th style="width:30%"><?php echo p__("cabride", "Label") ?></th>
                                    <th style="width:30%"><?php echo p__("cabride", "Type") ?></th>
                                    <th style="width:30%"><?php echo p__("cabride", "Default") ?></th>
                                    <th style="width:5%"><?php echo p__("cabride", "Required") ?></th>
                                    <th style="width:5%;"><?php echo p__("cabride", "Position") ?></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody class="fields-sortable">
                                <?php foreach ($fields as $field) : ?>
                                    <tr id="field_manage_element_<?php echo $field->getId(); ?>"
                                        rel="<?php echo $field->getId(); ?>"
                                        class="field-manage-element sb-pager field-container">
                                        <td class="field-handle"
                                            style="text-align: center;">
                                            <i class="fa fa-sort"
                                               style="margin-top: 11px;"></i>
                                        </td>
                                        <td>
                                            <h5 style="font-weight: bold;"><?php echo $field->getLabel() ?></h5>
                                        </td>
                                        <td>
                                            <?php echo $field->getFieldType() ?>
                                        </td>
                                        <td><?php echo $field->getDefaultValue() ?></td>
                                        <td>
                                            <?php if ($field->getIsRequired()): ?>
                                                <p class="label label-success"><?php echo p__("cabride", "YES") ?></p>
                                            <?php else: ?>
                                                <p class="label label-danger"><?php echo p__("cabride", "NO") ?></p>
                                            <?php endif; ?>
                                        </td>
                                        <td class="field-position"><?php echo $field->getPosition() ?></td>
                                        <td class="edit-action open-edit"
                                            data-id="field_<?php echo $field->getId(); ?>"
                                            data-form-url="<?php echo __path("/cabride/field/load-form", [
                                                "field_id" => $field->getId(),
                                                "value_id" => $valueId
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                            $deleteFieldForm->setAttrib("data-rowid", "field_manage_element_" . $field->getId());
                                            $deleteFieldForm->getElement("field_id")->setValue($field->getId());

                                            echo $deleteFieldForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="field_<?php echo $field->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="8">
                                            <p class="close-edit"
                                               data-id="field_<?php echo $field->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo p__("cabride", "Close") ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>





            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        bindForms("#fields");

        $("table.sb-pager.table-fields").sbpager({
            with_search: true,
            items_per_page: 1000,
            search_placeholder: "<?php echo __("Search ...") ?>",
            callback_goto_page: function() {
                $("table.sb-pager tr.edit-form[data-id]").hide()
            }
        });

        // Sections
        $('.fields-sortable').sortable({
            handle: ".field-handle",
            axis: "y",
            items: " .field-container",
            opacity: 0.85,
            start: function() {
                // Clear all forms inside elements!
                $("#fields .close-edit").trigger("click");
            },
            stop: function() {
                let sections = $('.fields-sortable tr[rel]');
                let data = {
                    indexes: []
                };
                let index = 1;
                sections.each(function() {
                    let el = $(this);
                    data.indexes.push(el.attr('rel'));

                    el.find('.field-position').text(index++);
                });

                formget(
                    '/cabride/field/update-positions',
                    data,
                    function(result) {},
                    function(result) {}
                );
            }
        });

        window.toggleGroups = function (formId, type) {
            $("#" + formId + " dd[id^='group_']").hide();

            switch (type) {
                case "number":
                    $("#" + formId + " #group_number-element").show();
                    break;
                case "date":
                    $("#" + formId + " #group_date-element").show();
                    break;
                case "datetime":
                    $("#" + formId + " #group_datetime-element").show();
                    break;
                default:
            }

            $("#" + formId + " [name='is_required']").parents(".sb-form-line").hide();

            switch (type) {
                case "text":
                case "textarea":
                case "datetime":
                case "date":
                case "number":
                case "password":
                    $("#" + formId + " [name='is_required']").parents(".sb-form-line").show();
                    break;
                default:
            }
        };

        window.toggleGroups("form-edit-field", "custom");

        window.binderFormField = function (formId) {
            let typeFields = $("#" + formId + " [name='field_type']");

            typeFields.off("change");
            typeFields.on("change", function () {
                let type = $(this).val();

                window.toggleGroups(formId, type);
            });
        };

        window.binderFormField("form-edit-field");
    });
</script>

<style type="text/css">
    #design .change_layout_handler img {
        max-height: 210px;
    }
</style>