<?php

use Cabride\Model\Cabride;
use Cabride\Model\Request;
use Cabride\Model\Stripe\Currency;
use Core\Model\Base;

$application = $this->getApplication();
$request = $this->getRequest();
$valueId = Cabride::getCurrentValueId();
$cabride = (new Cabride())->find($valueId, "value_id");

$rides = (new Request())->findAll([
    "value_id = ?" => $valueId,
], [
    "created_at DESC"
], [
    "limit" => 1000 // Only 1000 last ride requests for now.
]);

$du = $cabride->getDistanceUnit();
$cu = $cabride->getCurrency();
$cs = Currency::getCurrency($cabride->getCurrency())["symbol_native"];

function colorForStatus ($status) {
    switch ($status) {
        case "pending":
            return "label-info";
        case "onway":
        case "inprogress":
        case "accepted":
            return "label-info";
        case "done":
            return "label-success";
        case "declined":
        case "aborted":
            return "label-danger";
        case "expired":
            return "label-warning";
        default:
            return "label-info";
    }
}

?>
<div class="row cabride-rides">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="apis_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "Ride requests"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">
                        <table class="table content-white-bkg sb-pager margin-top">
                            <thead>
                            <tr class="border-grey">
                                <th class="sortable numeric"><?php echo p__("cabride", "ID"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Client"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Driver"); ?></th>
                                <th class="sortable numeric text-right"><?php echo p__("cabride", "Dist. / Dur."); ?></th>
                                <th class="sortable numeric text-right"><?php echo p__("cabride", "Est. cost"); ?></th>
                                <th class="sortable numeric text-right"><?php echo p__("cabride", "Cost"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Ride"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Status"); ?></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($rides as $ride): ?>
                                <tr class="sb-pager">
                                    <td>
                                        <b>#<?php echo $ride->getId(); ?></b>
                                    </td>
                                    <td>
                                        <a class="btn btn-xs btn-info"
                                           href="<?php echo __path("/cabride/dashboard/users?q={$ride->getClientId()}"); ?>">
                                            #<?php echo $ride->getClientId(); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-xs btn-info"
                                           href="<?php echo __path("/cabride/driver/edit", [
                                               "driver_id" => $ride->getDriverId()
                                           ]); ?>">
                                            #<?php echo $ride->getDriverId(); ?>
                                        </a>
                                    </td>
                                    <td class="text-right">
                                        <?php echo round($ride->getDistance() / 1000, 1); ?> <?php echo $du ?>
                                        -
                                        <?php echo $durationMinute = ceil($ride->getDuration() / 60); ?> mn
                                    </td>
                                    <td class="text-right">
                                        <?php if ($ride->getEstimatedCost() == $ride->getEstimatedLowestCost()): ?>
                                            <?php echo Base::_formatPrice($ride->getEstimatedCost(), $cu); ?>
                                        <?php else: ?>
                                            <?php echo Base::_formatPrice($ride->getEstimatedLowestCost(), $cu); ?>
                                            -
                                            <?php echo Base::_formatPrice($ride->getEstimatedCost(), $cu); ?>
                                        <?php endif; ?>
                                    </td>
                                    <td class="text-right">
                                        <?php if ($ride->getCost() <= 0): ?>
                                            -
                                        <?php else: ?>
                                            <?php if ($ride->getPaymentType() === "credit-card"): ?>
                                                <img style="height: 20px;"
                                                     src="/app/local/modules/Cabride/features/cabride/assets/templates/images/009-credit-card.svg" />
                                            <?php else: ?>
                                                <img style="height: 20px;"
                                                     src="/app/local/modules/Cabride/features/cabride/assets/templates/images/010-money.svg" />
                                            <?php endif; ?>
                                            <?php echo Base::_formatPrice($ride->getCost(), $cu); ?></td>
                                        <?php endif; ?>
                                    <td>
                                        <?php echo $ride->getFromAddress(); ?><br />
                                        <?php echo $ride->getToAddress(); ?>
                                    </td>
                                    <td>
                                        <span class="label <?php echo colorForStatus($ride->getStatus()) ?>">
                                                <?php echo p__("cabride", $ride->getStatus()); ?>
                                        </span>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="9">
                                        <?php echo p__("cabride", "No results for your search.") ?>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var searchPlaceholder = '<?php echo __js("Search ...", "'") ?>';
    $(document).ready(function () {
        bindForms("#vehicle_content");

        $("table.sb-pager").sbpager({
            with_search: true,
            search_placeholder: searchPlaceholder
        });
    });
</script>
<style type="text/css">
    .cabride-rides .label {
        font-size: 80%;
        font-weight: 200;
        letter-spacing: 2px;
        text-transform: uppercase;
        padding: .2em .4em .2em;
    }
</style>
