<?php

use Cabride\Model\Cabride;
use Cabride\Model\Request;
use Cabride\Model\Stripe\Currency;
use Core\Model\Base;

$application = $this->getApplication();
$request = $this->getRequest();
$valueId = Cabride::getCurrentValueId();

$cabride = (new Cabride())->find($valueId, "value_id");
if (!$cabride->getId()) {
    $cabride->setValueId($valueId);
    $cabride->save();
    $cabride->reload();
}

$rides = (new Request())->findAllWithUsers($valueId);

$du = $cabride->getDistanceUnit();
$cu = $cabride->getCurrency();
$cs = Currency::getCurrency($cabride->getCurrency())["symbol_native"];

function colorForStatus ($status) {
    switch ($status) {
        case "pending":
            return "label-info";
        case "onway":
        case "inprogress":
        case "accepted":
            return "label-info";
        case "done":
            return "label-success";
        case "declined":
        case "aborted":
            return "label-danger";
        case "expired":
            return "label-warning";
        default:
            return "label-info";
    }
}

$averageDistance = 0;
$averageDuration = 0;
$averageCost = 0;
$averageItems = 0;

$sumRating = 0;
$ratingItems = 0;

foreach ($rides as $ride) {
    $rating = $ride->getCourseRating();
    if ($rating > 0) {
        $ratingItems++;
        //
        $sumRating += $rating;
    }

    if ($ride->getStatus() === "done") {
        $averageItems++;
        //
        $averageDistance += $ride->getDistance() ? $ride->getDistance() / 1000 : 0;
        $averageDuration += $ride->getDuration() ? $ride->getDuration() / 60 : 0;
        $averageCost += $ride->getCost();
    }
}

if ($averageItems === 0) {
    $averageItems = 1;
}
$avgCost = $averageCost / $averageItems;
if (!is_numeric($avgCost) || is_nan($avgCost)) {
    $avgCost = 0;
}

if ($averageItems > 0) {
    $averageDistance = round($averageDistance / $averageItems, 1);
    $averageDuration = ceil($averageDuration / $averageItems);
} else {
    $averageDistance = 'N.A.';
    $averageDuration = 'N.A.';
}

if ($ratingItems > 0) {
    $averageRating = round($sumRating / $ratingItems, 2);
} else {
    $averageRating = 'N.A.';
}

$averageCost = Base::_formatPrice($avgCost, $cu);

$now = time();
$ridesToday = (new Request())->ridesForDate($valueId, date('Y-m-d', $now) . '%');

$week = $now;
$ridesWeek = (new Request())->ridesForDate($valueId, date('Y-m-d', $week) . '%');
$ridesWeek += (new Request())->ridesForDate($valueId, date('Y-m-d', $week-=86400) . '%');
$ridesWeek += (new Request())->ridesForDate($valueId, date('Y-m-d', $week-=86400) . '%');
$ridesWeek += (new Request())->ridesForDate($valueId, date('Y-m-d', $week-=86400) . '%');
$ridesWeek += (new Request())->ridesForDate($valueId, date('Y-m-d', $week-=86400) . '%');
$ridesWeek += (new Request())->ridesForDate($valueId, date('Y-m-d', $week-=86400) . '%');
$ridesWeek += (new Request())->ridesForDate($valueId, date('Y-m-d', $week-=86400) . '%');

$ridesMonth = (new Request())->ridesForDate($valueId, date('Y-m', $now) . '%');
$ridesYear = (new Request())->ridesForDate($valueId, date('Y', $now) . '%');


?>
<div class="row cabride-rides">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="apis_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "Ride requests"); ?>
                </h3>
                <div class="subcontent content-color">

                    <div class="col-md-3">
                        <div class="alert alert-info text-center">
                            <p class="dashboard-income"><?php echo $averageDistance ?> <?php echo $du ?></p>
                            <p class="income-more">
                                <?php echo p__("cabride", "AVERAGE DISTANCE"); ?>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-warning text-center">
                            <p class="dashboard-income"><?php echo $averageDuration ?> mn</p>
                            <p class="income-more">
                                <?php echo p__("cabride", "AVERAGE DURATION"); ?>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-success text-center">
                            <p class="dashboard-income"><?php echo $averageCost ?></p>
                            <p class="income-more">
                                <?php echo p__("cabride", "AVERAGE FARE"); ?>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-danger text-center">
                            <p class="dashboard-income"><?php echo $averageRating ?> <i class="fa fa-star"></i></p>
                            <p class="income-more">
                                <?php echo p__("cabride", "AVERAGE RATING"); ?>
                            </p>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="alert alert-warning text-center">
                            <p class="dashboard-income"><?php echo $ridesToday ?></p>
                            <p class="income-more">
                                <?php echo p__("cabride", "RIDES TODAY"); ?>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-success text-center">
                            <p class="dashboard-income"><?php echo $ridesWeek ?></p>
                            <p class="income-more">
                                <?php echo p__("cabride", "RIDES LAST 7 DAYS"); ?>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-danger text-center">
                            <p class="dashboard-income"><?php echo $ridesMonth ?></p>
                            <p class="income-more">
                                <?php echo p__("cabride", "RIDES THIS MONTH"); ?>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-info text-center">
                            <p class="dashboard-income"><?php echo $ridesYear ?></p>
                            <p class="income-more">
                                <?php echo p__("cabride", "RIDES THIS YEAR"); ?>
                            </p>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <table class="table content-white-bkg sb-pager margin-top high-contrast">
                            <thead>
                            <tr class="border-grey">
                                <th class="sortable numeric"><?php echo p__("cabride", "ID"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Client"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Driver"); ?></th>
                                <th class="sortable numeric"><?php echo p__("cabride", "Date"); ?></th>
                                <th class="sortable numeric text-right"><?php echo p__("cabride", "Dist. / Dur."); ?></th>
                                <th class="sortable numeric text-right"><?php echo p__("cabride", "Est. cost"); ?></th>
                                <th class="sortable numeric text-right"><?php echo p__("cabride", "Cost"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Ride"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Rating"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Status"); ?></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($rides as $ride): ?>
                                <tr class="sb-pager <?php echo $ride->getStatus() ?>">
                                    <td>
                                        <b>#<?php echo $ride->getId(); ?></b>
                                    </td>
                                    <td>
                                        <a class="btn btn-xs btn-info"
                                           href="<?php echo __path("/cabride/dashboard/users?q={$ride->getClientId()}"); ?>">
                                            #<?php echo $ride->getClientId(); ?>
                                        </a>
                                        <br />
                                        <?php echo sprintf("%s %s", $ride->getCustomerFirstname(), $ride->getCustomerLastname()) ?>
                                    </td>
                                    <td>
                                        <?php if ($ride->getDriverId() > 0): ?>
                                        <a class="btn btn-xs btn-info"
                                           href="<?php echo __path("/cabride/driver/edit", [
                                               "driver_id" => $ride->getDriverId()
                                           ]); ?>">
                                            #<?php echo $ride->getDriverId(); ?>
                                        </a>
                                        <br />
                                        <?php echo sprintf("%s %s", $ride->getDriverFirstname(), $ride->getDriverLastname()) ?>
                                        <?php else: ?>
                                        <span class="label <?php echo colorForStatus($ride->getStatus()) ?>">
                                            <?php echo p__('cabride', 'N.A.') ?>
                                        </span>
                                        <?php endif; ?>
                                    </td>
                                    <td>
                                        <span style="display: none"><?php echo datetime_to_format($ride->getCreatedAt(), Zend_Date::TIMESTAMP) ?></span>
                                        <?php echo datetime_to_format($ride->getCreatedAt(), Zend_Date::DATETIME_SHORT) ?>
                                    </td>
                                    <td class="text-right">
                                        <?php echo round($ride->getDistance() / 1000, 1); ?> <?php echo $du ?>
                                        -
                                        <?php echo $durationMinute = ceil($ride->getDuration() / 60); ?> mn
                                    </td>
                                    <td class="text-right">
                                        <?php if ($ride->getEstimatedCost() == $ride->getEstimatedLowestCost()): ?>
                                            <?php echo Base::_formatPrice($ride->getEstimatedCost(), $cu); ?>
                                        <?php else: ?>
                                            <?php echo Base::_formatPrice($ride->getEstimatedLowestCost(), $cu); ?>
                                            -
                                            <?php echo Base::_formatPrice($ride->getEstimatedCost(), $cu); ?>
                                        <?php endif; ?>
                                    </td>
                                    <td class="text-right">
                                        <?php if ($ride->getCost() <= 0): ?>
                                            -
                                        <?php else: ?>
                                            <?php if ($ride->getPaymentType() === "credit-card"): ?>
                                                <img style="height: 20px;"
                                                     src="/app/local/modules/Cabride/features/cabride/assets/templates/images/009-credit-card.svg" />
                                            <?php else: ?>
                                                <img style="height: 20px;"
                                                     src="/app/local/modules/Cabride/features/cabride/assets/templates/images/010-money.svg" />
                                            <?php endif; ?>
                                            <?php echo Base::_formatPrice($ride->getCost(), $cu); ?></td>
                                        <?php endif; ?>
                                    <td>
                                        <?php echo $ride->getFromAddress(); ?><br />
                                        <?php echo $ride->getToAddress(); ?>
                                    </td>
                                    <td>
                                        <?php if ($ride->getCourseRating() > 0): ?>
                                            <?php for ($i = 0; $i < $ride->getCourseRating(); $i++): ?>
                                            <i class="fa fa-star"></i>
                                            <?php endfor; ?>
                                        <?php else: ?>
                                            <?php echo p__("cabride", "n.c."); ?>
                                        <?php endif;  ?>
                                    </td>
                                    <td>
                                        <span class="label <?php echo colorForStatus($ride->getStatus()) ?>">
                                            <?php echo p__("cabride", $ride->getStatus()); ?>
                                        </span>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="9">
                                        <?php echo p__("cabride", "No results for your search.") ?>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var searchPlaceholder = '<?php echo __js("Search ...", "'") ?>';
    $(document).ready(function () {
        bindForms("#vehicle_content");

        $("table.sb-pager").sbpager({
            with_search: true,
            search_placeholder: searchPlaceholder
        });
    });
</script>
<style type="text/css">
    .cabride-rides .label {
        font-size: 80%;
        font-weight: 200;
        letter-spacing: 2px;
        text-transform: uppercase;
        padding: .2em .4em .2em;
    }

    @import url("https://fonts.googleapis.com/css?family=Titillium+Web&text=0123456789%C2%A3$%E2%82%AC.,");

    p.dashboard-income {
        font-family: "Titillium Web", monospace;
        font-size: 3rem;
    }

    p.income-hint {
        font-size: 1.2rem;
        padding: 0 0 10px;
        line-height: 1.8rem;
    }

    p.income-more {
        margin: -13px;
        padding: 10px;
        font-size: 1rem;
        text-align: center;
    }

    .alert-info p.income-more {
        background-color: #48829e;
    }

    .alert-warning p.income-more {
        background-color: #966e25;
    }

    .alert-success p.income-more {
        background-color: #3c763d;
    }

    .alert-danger p.income-more {
        background-color: #823231;
    }

    table.high-contrast {
        color: #202020;
    }
    table.high-contrast tr {
        border-bottom: 1px solid #e2e2e2;
    }
    table.high-contrast tr.done {
        border-left: 4px solid #5cb85c;
    }
    table.high-contrast tr.aborted {
        border-left: 4px solid #d9534f;
    }
    table.high-contrast tr.expired {
        border-left: 4px solid #f0ad4e;
    }
</style>
