<?php

use Cabride\Model\Cabride;
use Cabride\Form\Cabride as FormCabride;
use Cabride\Form\Gateway\Stripe as FormStripe;
use Cabride\Form\Gateway\Twocheckout as FormTwocheckout;
use Cabride\Form\Gateway\Braintree as FormBraintree;

$application = $this->getApplication();
$request = $this->getRequest();
$valueId = Cabride::getCurrentValueId();

$formSettings = new FormCabride();
$formSettings->setValueId($valueId);

$settings = (new Cabride())
    ->find($valueId, "value_id");
$settings = (new Cabride())->find($valueId, "value_id");
if (!$settings->getId()) {
    $settings->setValueId($valueId);
    $settings->save();
    $settings->reload();
}

$formStripe = new FormStripe();
$formStripe->setValueId($valueId);

$formTwocheckout = new FormTwocheckout();
$formTwocheckout->setValueId($valueId);

$formBraintree = new FormBraintree();
$formBraintree->setValueId($valueId);

if ($settings->getId()) {
    $settingsData = $settings->getData();

    $formSettings->populate($settingsData);
    $formStripe->populate($settingsData);
    $formTwocheckout->populate($settingsData);
    $formBraintree->populate($settingsData);
}

?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="settings_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "CabRide settings"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">
                        <?php echo $formSettings ?>

                    </div>
                </div>
            </div>

            <div id="apis_content"
                 class="content solo-page sb-tour">

                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "Payment API credentials"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">
                        <div class="form-payment"
                             rel="stripe">
                            <h4 class="title-editor no-border-radius title-feature-indent">
                                <?php echo p__("cabride", "Stripe") ?>
                            </h4>
                            <div class="container-fluid content-feature">
                                <br />
                                <?php echo $formStripe ?>
                            </div>

                            <br />
                        </div>

                        <div class="form-payment"
                             rel="twocheckout">
                            <h4 class="title-editor no-border-radius title-feature-indent">
                                <?php /**echo p__("cabride", "2Checkout")*/ ?>
                            </h4>
                            <div class="container-fluid content-feature">
                                <br />
                                <?php echo $formTwocheckout ?>
                            </div>

                            <br />
                        </div>

                        <div class="form-payment"
                             rel="braintree">
                            <h4 class="title-editor no-border-radius title-feature-indent">
                                <?php /**echo p__("cabride", "BrainTree")*/ ?>
                            </h4>
                            <div class="container-fluid content-feature">
                                <br />
                                <?php echo $formBraintree ?>
                            </div>
                        </div>

                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function () {
    bindForms("#settings_content");
    bindForms("#apis_content");

    let commissionType = $("#commission_type");

    commissionType.off("change");
    commissionType.on("change", function () {
        updateCommission();
    });

    let updateCommission = function () {
        let value = commissionType.val();
        switch (value) {
            case "disabled":
                $("#commission").parents(".sb-form-line").hide();
                $("#commission_fixed").parents(".sb-form-line").hide();
                break;
            case "fixed":
                $("#commission").parents(".sb-form-line").hide();
                $("#commission_fixed").parents(".sb-form-line").show();
                break;
            case "percentage":
                $("#commission").parents(".sb-form-line").show();
                $("#commission_fixed").parents(".sb-form-line").hide();
                break;
            case "mixed":
                $("#commission").parents(".sb-form-line").show();
                $("#commission_fixed").parents(".sb-form-line").show();
                break;
        }
    };

    updateCommission();

    let paymentProvider = $("#payment_provider");

    paymentProvider.off("change");
    paymentProvider.on("change", function () {
        updatePaymentProvider();
    });

    let updatePaymentProvider = function () {
        $(".form-payment").hide();
        let value = paymentProvider.val();
        $(".form-payment[rel='" + value + "']").show();
    };

    updatePaymentProvider();
});
</script>
<style type="text/css">
    #settings_content fieldset {
        border-left: 1px solid grey;
        margin-bottom: 15px;
    }

    #settings_content fieldset legend {
        margin-top: 0;
        margin-bottom: 0;
        text-transform: uppercase;
        font-weight: 100;
        letter-spacing: 0.05em;
        background: white;
        font-size: 18px;
        text-indent: 5px;
        border-left: 1px solid grey;
        margin-left: -1px;
        padding: 5px;
    }

    #settings_content fieldset dl {
        padding: 15px;
        margin-bottom: 0;
        padding-bottom: 0;
    }
</style>