<?php
$application = $this->getApplication();
$request = $this->getRequest();

$formSettings = new Cabride_Form_Cabride();
?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="apis_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo __("CabRide Settings"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">
                        <?php

                        ?>
                        <?php echo $formSettings ?>

                        <h1>APIs de paiements 2 day</h1>
                        <ul>
                            <li>Stripe</li>
                            <li>2Checkout</li>
                            <li>Paypal?</li>
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

</script>
