<?php

use Cabride\Model\Cabride;

?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="translations_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "CabRide translations"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">
                        <?php /**echo $formSettings*/ ?>

                    </div>
                </div>
            </div>


        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function () {
    bindForms("#translations_content");

});
</script>
<style type="text/css">
    #translations_content fieldset {
        border-left: 1px solid grey;
        margin-bottom: 15px;
    }

    #translations_content fieldset legend {
        margin-top: 0;
        margin-bottom: 0;
        text-transform: uppercase;
        font-weight: 100;
        letter-spacing: 0.05em;
        background: white;
        font-size: 18px;
        text-indent: 5px;
        border-left: 1px solid grey;
        margin-left: -1px;
        padding: 5px;
    }

    #translations_content fieldset dl {
        padding: 15px;
        margin-bottom: 0;
        padding-bottom: 0;
    }
</style>
