<?php

use Gettext\Translations;

$originalTranslations = new Translations();
$originalTranslations->addFromPoFile(path('/app/local/modules/Cabride/resources/translations/default/cabride.po'));

$application = $this->getApplication();
$appId = $application->getId();

$existingLanguages = Core_Model_Language::getLanguageCodes();
$currentLang = Core_Model_Language::getCurrentLanguage();

$translations = [];
$userTranslations = [];
$existingLanguages = array_unique($existingLanguages);
foreach ($existingLanguages as $existingLanguage) {
    $userTranslations[$existingLanguage] = [];

    $path = path("/languages/{$existingLanguage}/cabride.po");
    if (!is_readable($path)) {
        continue;
    }
    $_tmpTranslations = new Translations();
    $_tmpTranslations->addFromPoFile($path);

    $translations[$existingLanguage] = $_tmpTranslations;
}

$locale = Zend_Registry::get('Zend_Locale');
$languages = $locale->getTranslationList('language', new Zend_Locale($currentLang));
foreach ($languages as $k => $language) {
    if (!$locale->isLocale($k) && !in_array($k, $existingLanguages, false)) {
        unset($languages[$k]);
    }
}
unset($languages['root']);

asort($languages, SORT_LOCALE_STRING);
$languages = array_map('ucfirst', $languages);

$dbTranslations = (new \Cabride\Model\Translation())->findAll([
    'app_id = ?' => $appId
]);
foreach ($dbTranslations as $dbTranslation) {
    $_db_key = base64_decode($dbTranslation->getData('original'));
    $_db_value = base64_decode($dbTranslation->getTranslation());
    $_db_locale = $dbTranslation->getLocale();

    if (array_key_exists($_db_locale, $userTranslations) && !empty($_db_value)) {
        $userTranslations[$_db_locale][$_db_key] = $_db_value;
    }
}

$totalCount = count($originalTranslations);

?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="translations_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__('cabride', 'CabRide translations'); ?>
                </h3>
                <div class="subcontent content-color">
                    <form id="form-locales">
                        <div class="col-md-6">
                            <label>
                                <?php echo p__('cabride', 'Select a locale to customize') ?>
                                <select id="change-lang"
                                        class="sb-select styled-select color-blue form-control no-dk">
                                    <?php foreach ($existingLanguages as $code): ?>
                                        <option value="<?php echo $code ?>"
                                            <?php echo $code === $currentLang ? 'selected="selected"' : '' ?>>
                                            <?php echo $languages[$code] ?>
                                            (<?php echo count($userTranslations[$code]) ?>/<?php echo $totalCount ?>)
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </label>
                            <br/>
                            <br/>
                        </div>

                        <div class="col-md-6">
                            <button class="btn default_button color-blue pull-right"
                                    type="submit"><?php echo p__('cabride', 'Save') ?></button>
                            <div style="clear: both;"></div>
                        </div>

                        <div class="clear col-md-12">

                            <table class="table table-translations">
                                <thead>
                                    <tr class="second-tr">
                                        <?php $i = 0;
                                        foreach ($existingLanguages as $language): $i++ ?>
                                            <th class="bg-white"
                                                style="width: 50%;"
                                                rel="<?php echo $language; ?>"><?php echo p__('cabride', 'Default') ?></th>
                                            <th class="bg-white"
                                                style="width: 50%;"
                                                rel="<?php echo $language; ?>"><?php echo p__('cabride', 'Yours') ?></th>
                                        <?php endforeach; ?>
                                    </tr>
                                </thead>
                                <tbody style="display: none;">
                                <?php
                                $indexI = 0;
                                $indexJ = 0;
                                foreach ($originalTranslations as $key => $originalTranslation):
                                    $indexI++;
                                    echo "<tr class=\"translation\">";
                                    foreach ($existingLanguages as $code):
                                        $indexJ++;
                                        $_originalKey = $originalTranslation->getOriginal();
                                        $_tmpTr = $translations[$code] ?? [];
                                        if (!is_array($_tmpTr)) {
                                            $_tmpTr = [];
                                        }
                                        $_userValue = '';
                                        if (array_key_exists($code, $userTranslations) && array_key_exists($_originalKey, $userTranslations[$code])) {
                                            $_userValue = htmlentities($userTranslations[$code][$_originalKey]);
                                        }
                                        if (array_key_exists($key, $_tmpTr)) {
                                            ?>
                                            <td rel="<?php echo $code ?>"
                                                ref="<?php echo $code ?>-<?php echo $indexI ?>-<?php echo $indexJ ?>">
                                                <?php echo $_tmpTr[$key]->getTranslation() ?>
                                                <?php if (count($originalTranslation->getFlags()) > 0): ?>
                                                    <span class="badge">#<?php echo $originalTranslation->getFlags()[0] ?></span>
                                                <?php endif; ?>
                                            </td>
                                            <td rel="<?php echo $code ?>"
                                                ref="<?php echo $code ?>-<?php echo $indexI ?>-<?php echo $indexJ ?>">
                                                <input type="text"
                                                       name="tr[<?php echo $code ?>][<?php echo $originalTranslation->getOriginal() ?>][value]"
                                                       rel="<?php echo $code ?>"
                                                       ref="<?php echo $code ?>-<?php echo $indexI ?>-<?php echo $indexJ ?>"
                                                       class="input-flat input-translation"
                                                       value="<?php echo trim($_userValue); ?>"/>
                                            </td>
                                            <?php
                                        } else {
                                            ?>
                                            <td rel="<?php echo $code ?>"
                                                ref="<?php echo $code ?>-<?php echo $indexI ?>-<?php echo $indexJ ?>">
                                                <i><?php echo $originalTranslation->getOriginal() ?></i>
                                            </td>
                                            <td rel="<?php echo $code ?>"
                                                ref="<?php echo $code ?>-<?php echo $indexI ?>-<?php echo $indexJ ?>">
                                                <input type="text"
                                                       name="tr[<?php echo $code ?>][<?php echo $originalTranslation->getOriginal() ?>][value]"
                                                       rel="<?php echo $code ?>"
                                                       ref="<?php echo $code ?>-<?php echo $indexI ?>-<?php echo $indexJ ?>"
                                                       class="input-flat input-translation"
                                                       value="<?php echo trim($_userValue); ?>"/>
                                            </td>
                                            <?php
                                        }
                                    endforeach;
                                    echo "</tr>";
                                endforeach;
                                ?>
                                </tbody>
                            </table>

                            <button class="btn default_button color-blue pull-right"
                                    type="submit"><?php echo p__('cabride', 'Save') ?></button>

                        </div>
                    </form>
                </div>
            </div>


        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        let currentLang = '<?php echo $currentLang ?>';

        let toggleLanguage = function (code) {
            $('th[rel], td[rel]').hide();
            $('th[rel="' + code + '"], td[rel="' + code + '"]').show();
            currentLang = code;
        };

        let _cabSubmit = function (uri, formData) {
            loader.show('sb-formget');

            $.ajax({
                type: 'POST',
                url: uri,
                data: formData,
                dataType: 'json',
                success: function (data) {
                    if (data.success) {
                        feature_form_success(data.message || data.success_message);
                    } else if (data.warning) {
                        feature_form_warning(data.message);
                    } else if (data.error) {
                        feature_form_error(data.message);
                    } else {
                        feature_form_error('An error occured, please try again.');
                    }

                    loader.hide('sb-formget');
                },
                error: function (data) {
                    feature_form_error(data.message, data.message_timeout);

                    loader.hide('sb-formget');
                }
            });
        };

        let formTr = $('#form-locales');
        formTr.off('submit');
        formTr.on('submit', function (e) {
            e.preventDefault();
            let values = $('#form-locales input[rel="' + currentLang + '"]').serialize();
            _cabSubmit('/cabride/translation/save', values);
        });

        let selectLang = $('#change-lang');
        selectLang.off('change');
        selectLang.on('change', function () {
            toggleLanguage($(this).val());
        });

        toggleLanguage(currentLang);

        let toggleInputClassEl = function (el) {
            let ref = el.attr('ref');
            let refCells = $('td[ref="' + ref + '"]');
            refCells
                .removeClass('success')
                .removeClass('info');

            if (el.val().trim().length > 0) {
                refCells.addClass('success');
            } else {
                refCells.addClass('info');
            }
        };

        let toggleInputClass = function ()
        {
            $('.input-translation').each(function (index, el) {
                toggleInputClassEl($(el));
            });
        };

        let inputTr = $('.input-translation');
        inputTr.off('keyup');
        inputTr.on('keyup', function () {
            toggleInputClassEl($(this));
        });

        toggleInputClass();

        // Show body only when ready!
        $('table.table-translations tbody').show();
    });
</script>
<style type="text/css">
    #translations_content fieldset {
        border-left: 1px solid grey;
        margin-bottom: 15px;
    }

    #translations_content fieldset legend {
        margin-top: 0;
        margin-bottom: 0;
        text-transform: uppercase;
        font-weight: 100;
        letter-spacing: 0.05em;
        background: white;
        font-size: 18px;
        text-indent: 5px;
        border-left: 1px solid grey;
        margin-left: -1px;
        padding: 5px;
    }

    #translations_content fieldset dl {
        padding: 15px;
        margin-bottom: 0;
        padding-bottom: 0;
    }

    tr.second-tr th {
        border: 0 !important;
        border-bottom: 2px solid #949494 !important;
        background-color: #ffffff;
    }

    table.table-translations {

    }

    tr.translation td {
        border-bottom: 1px solid lightgrey;
        vertical-align: middle !important;
    }
</style>
