<?php
$application = $this->getApplication();
$request = $this->getRequest();
?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="apis_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo __("CabRide Users"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">
                        <?php

                        ?>
                        <h1>// 1. List & Manage users 2 days</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

</script>
