<?php
$application = $this->getApplication();
$request = $this->getRequest();
$valueId = Cabride_Model_Cabride::getCurrentValueId();

$formVehicleType = new Cabride_Form_Vehicle();
$formVehicleType->setValueId($valueId);

$vehicles = (new Cabride_Model_Vehicle())
    ->findAll(["value_id" => $valueId]);

?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="apis_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "CabRide vehicle types"); ?>
                </h3>
                <div class="subcontent content-color">

                    <div id="form-vehicle-type"
                         class="col-md-12"
                         style="display:none;">

                        <div>
                            <button class="toggle-form btn color-blue pull-right">
                                <?php echo p__("cabride", "Close"); ?>
                            </button>
                        </div>

                        <?php echo $formVehicleType ?>
                    </div>

                    <div class="col-md-12">
                        <div style="margin: 15px 0 15px 0;">
                            <button class="toggle-form btn color-blue pull-right">
                                <?php echo p__("cabride", "Add a vehicle type"); ?>
                            </button>

                            <div style="clear: both;"></div>
                        </div>

                        <table class="table table-striped margin-top">
                            <thead>
                                <tr class="content-white-bkg">
                                    <th><?php echo p__("cabride", "ID"); ?></th>
                                    <th><?php echo p__("cabride", "Vehicle type"); ?></th>
                                    <th><?php echo p__("cabride", "Is visible?"); ?></th>
                                    <th><?php echo p__("cabride", "Base fare"); ?></th>
                                    <th><?php echo p__("cabride", "Distance fare"); ?></th>
                                    <th><?php echo p__("cabride", "Time fare"); ?></th>
                                    <th><?php echo p__("cabride", "Base address"); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($vehicles as $vehicle): ?>
                                    <tr>
                                        <td><?php echo $vehicle->getId(); ?></td>
                                        <td><?php echo $vehicle->getType(); ?></td>
                                        <td><?php echo $vehicle->getIsVisible(); ?></td>
                                        <td><?php echo $vehicle->getBaseFare(); ?></td>
                                        <td><?php echo $vehicle->getDistanceFare(); ?></td>
                                        <td><?php echo $vehicle->getTimeFare(); ?></td>
                                        <td><?php echo $vehicle->getBaseAddress(); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function () {
    bindForms("#apis_content");

    let toggleForm = $(".toggle-form");
    let formVehicleType = $("#form-vehicle-type");

    toggleForm.off("click");
    toggleForm.on("click", function () {
        formVehicleType.toggle();
    });
});
</script>
